### ISSUE TITLE
Unhandled Rejection (Error): Requested texture size [8689x8689] greater than WebGL maximum on this browser / GPU [8192x8192]

### ISSUE THREAD

**Issue by SiddhantBahuguna** [mindee/doctr-tfjs-demo#25]
For inference with Resnet, I am getting the following error:
```Unhandled Rejection (Error): Requested texture size [8689x8689] greater than WebGL maximum on this browser / GPU [8192x8192]```

Please find the input image as:

![2](https://user-images.githubusercontent.com/90187114/143046204-48d8f569-b5c2-434d-92a5-aa6fd7ebc71d.jpg)

It is however working perfectly fine with MobileNet. Could you please have a look if you are also experiencing the same problem? 
Thanks a lot!

**Comment by fg-mindee** [comment]
If we can't get it to work, I suggest we remove the resnet backbone for now since the bundle is much bigger with it :upside_down_face:

**Comment by fharper** [comment]
They are both working with the latest version.
