### ISSUE TITLE
Docker v23.0.1 Get me Error

### ISSUE THREAD

**Issue by CICCIOSGAMINO** [mindee/doctr-tfjs-demo#61]
I've just trying to run the docker in my environment but i get the error: 

file:///usr/local/lib/node_modules/serve/build/main.js:169
      const ipAddress = request.socket.remoteAddress?.replace("::ffff:", "") ?? "unknown";
                                                     ^

SyntaxError: Unexpected token '.'
    at Loader.moduleStrategy (internal/modules/esm/translators.js:140:18)
    at async link (internal/modules/esm/module_job.js:42:21)

**Comment by artyuum** [comment]
Using node14 instead of node12 fixed it for me.

**Comment by paretl** [comment]
Hello @CICCIOSGAMINO , thanks for reporting the issue. I have fixed it with the commit https://github.com/mindee/doctr-tfjs-demo/commit/fcb8cc308b75017c20877ba986b5a6df37259d50
It is a quick fix, if you decided to use node14 instead of node12, that's great as well
